<a href="https://colab.research.google.com/github/rabinam24/NLP/blob/main/TextRepresentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Here we will do some Text Representation which is also known as feature extraction

# Text representation is converting the text into the numbers with the meaningful value, that's the meaning of text must be conserved while converting into the numbers

# First technique is the one hot encoding where we convert the text into corpus which meaning concatenating all the words, and defining the vocabulary which means identify the unique words present in the corpus and then we convert the text into the number which you can google and understand more deeply. The problem with this is that it create the sparsity and lost the meaning while converting into the numbers.

# Bag of words

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({'text':['people watch football','football watch football','people support team','football support team'],'output':[1,1,0,0]})


In [ ]:
df

text  output
0    people watch football       1
1  football watch football       1
2      people support team       0
3    football support team       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()

In [ ]:
bow =cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people': 1, 'watch': 4, 'football': 0, 'support': 2, 'team': 3}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 1 0 0 1]]
[[2 0 0 0 1]]


In [ ]:
cv.transform(['People support and watch football for the happiness of the people']).toarray()

array([[1, 2, 1, 0, 1]])

## Here above, we can see it is handeling out of the vocabulary problem easily like for the happiness of! but still it's has some problem considering the out of the vocabulary, sparsity,non-ordering of the words can create different meaning and can create problem and finally, for example: I like watching football, I don't like watching football, in this case since there is one word only difference, bag of words will tries to define the less difference in them with less angle. but They are completely different which can be solve by now ngrams.

# ngrams bigrams

In [ ]:
df1 = pd.DataFrame({'text':['people watch football','football watch football','people support team','football support team'],'output':[1,1,0,0]})


In [ ]:
df1

text  output
0    people watch football       1
1  football watch football       1
2      people support team       0
3    football support team       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(ngram_range=(2,2))

In [ ]:
bow =cv.fit_transform(df1['text'])

In [ ]:
print(cv.vocabulary_)

{'people watch': 3, 'watch football': 5, 'football watch': 1, 'people support': 2, 'support team': 4, 'football support': 0}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 0 1 0 1]]
[[0 1 0 0 0 1]]


# Tf-Idf (Term frequency-Inverse document frequency) concept is that it assign different values to different words present in the document based on tf-idf values

In [ ]:
df

text  output
0    people watch football       1
1  football watch football       1
2      people support team       0
3    football support team       0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.61366674, 0.        , 0.        , 0.61366674],
       [0.8508161 , 0.        , 0.        , 0.        , 0.52546357],
       [0.        , 0.57735027, 0.57735027, 0.57735027, 0.        ],
       [0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ]])

In [ ]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['football' 'people' 'support' 'team' 'watch']
