<a href="https://colab.research.google.com/github/rabinam24/NLP/blob/main/Word2Vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Word2Vec is the technique which convets words into vector like bag of words and tf-idf but the greatest advantanges of Word2Vec is that it provide the semantic meaning of the words. for example: happy, joy are the two words which are similar which are captured by word2vec but could not told by bag of words and tf-idf. Word2Vec create low dimensional vector and dense vector while bag of words,tf-idf create very high dimensional vector and sparse vector

In [93]:
import numpy as np
import pandas as pd
import gensim
import os
from gensim.models import Word2Vec,KeyedVectors
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [114]:
import os
from nltk import sent_tokenize, word_tokenize
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords

# Download stopwords (if not already downloaded)
import nltk
nltk.download('stopwords')

# Load English stopwords from NLTK
stop_words = set(stopwords.words('english'))

story = []

# Specify the correct directory path
directory_path = '/content/drive/MyDrive/Gameofthrones'

for filename in os.listdir(directory_path):
    file_path = os.path.join(directory_path, filename)

    with open(file_path, 'r', encoding='latin-1') as file:
        corpus = file.read()
        raw_sentences = sent_tokenize(corpus)

        for sent in raw_sentences:
            # Tokenize the sentence into words
            words = simple_preprocess(sent)

            # Remove stopwords
            filtered_words = [word for word in words if word.lower() not in stop_words]

            story.append(filtered_words)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [115]:
len(story)

145020

In [116]:
model = gensim.models.Word2Vec(
    window =7,
    min_count=2,
)

In [117]:
model.build_vocab(story)

In [118]:
model.train(story,total_examples=model.corpus_count,epochs=5)

(4397033, 4579390)

In [119]:
model.wv.most_similar('snow')

[('ghost', 0.7925394177436829),
 ('drifts', 0.6891258955001831),
 ('direwolf', 0.6863511204719543),
 ('walkers', 0.6863026022911072),
 ('ice', 0.6724848747253418),
 ('hut', 0.6708899736404419),
 ('falling', 0.661328136920929),
 ('blowing', 0.6585361957550049),
 ('messed', 0.6583698391914368),
 ('wilderness', 0.6546033620834351)]

In [120]:
model.wv.doesnt_match(['jon','robb','arya','sansa','bran'])

'jon'

In [121]:
model.wv['jon']

array([-1.6125494 ,  0.12199823,  1.8058399 , -1.1306142 ,  1.2138084 ,
       -0.08307205,  0.61758935,  1.5080128 ,  0.2601843 , -0.86110836,
       -0.9381605 , -2.2349005 , -0.7625448 , -0.16879992,  0.12993477,
       -0.5152637 ,  0.8561179 , -0.7838719 ,  0.5625418 , -0.34598386,
       -0.21297626,  0.79970115,  0.10166967,  0.06551219,  0.89651525,
        1.262704  , -1.9403106 ,  0.03862962,  0.6306743 ,  0.8901774 ,
       -0.61449707,  0.38276443, -0.08598521,  1.1650001 , -0.7862936 ,
       -0.45375484, -0.6959203 , -1.3984852 ,  0.5304865 , -0.68646854,
        0.23647851, -0.74138653, -0.03844474,  0.18701935, -0.49206787,
       -0.6241198 ,  0.02333559, -1.6952368 , -1.2310008 ,  2.419811  ,
        0.85797083, -1.4538049 ,  0.29571244, -1.6966109 ,  0.42546603,
        0.10456186,  0.57147026,  1.0610781 ,  1.0235134 ,  2.3118079 ,
       -1.0410315 , -1.0170853 ,  0.478072  , -0.44095194, -0.5888627 ,
        1.106424  ,  0.79186666,  0.6611885 ,  0.34379935,  0.32

In [122]:
model.wv['king'].shape

(100,)

In [123]:
model.wv.similarity('arya','sansa')

0.85486066

In [124]:
model.wv.similarity('tywin','sansa')

0.33714688

In [125]:
model.wv.get_normed_vectors()

array([[ 0.00037679,  0.02784139,  0.0243308 , ..., -0.02838043,
        -0.10525037,  0.19187777],
       [-0.11547804,  0.09340604,  0.07564414, ..., -0.08283535,
        -0.14210941,  0.14556922],
       [-0.00837291, -0.02166891, -0.0670299 , ..., -0.17237349,
         0.08933239, -0.08304239],
       ...,
       [ 0.02722531,  0.04178632, -0.01897849, ..., -0.10761733,
        -0.06080988,  0.17504095],
       [-0.06841125,  0.00885757,  0.16921751, ..., -0.00880747,
        -0.01629214,  0.18491594],
       [-0.14028661,  0.00760514,  0.00944154, ...,  0.05547703,
        -0.0935865 ,  0.13597609]], dtype=float32)

In [126]:
y= model.wv.index_to_key

In [127]:
y

['said',
 'lord',
 'would',
 'one',
 'ser',
 'could',
 'man',
 'king',
 'men',
 'back',
 'well',
 'like',
 'jon',
 'father',
 'old',
 'hand',
 'even',
 'tyrion',
 'never',
 'see',
 'know',
 'made',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'long',
 'might',
 'us',
 'come',
 'face',
 'still',
 'head',
 'red',
 'way',
 'boy',
 'page',
 'must',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 'little',
 'took',
 'came',
 'though',
 'say',
 'three',
 'away',
 'dead',
 'son',
 'blood',
 'take',
 'go',
 'half',
 'make',
 'arya',
 'saw',
 'day',
 'white',
 'jaime',
 'first',
 'look',
 'want',
 'much',
 'enough',
 'sword',
 'tell',
 'girl',
 'bran',
 'great',
 'looked',
 'left',
 'knew',
 'asked',
 'gave',
 'maester',
 'called',
 'wall',
 'every',
 'heard',
 'sansa',
 'let',
 'yet',
 'went',
 'turned',
 'dany',
 'behind',
 'need',
 'around',
 'woman',
 'another',
 'snow',
 'beneath',
 'across',
 'knight',
 'keep',
 'grace',
 'found',
 'gold',
 'last',
 'cersei',
 'castle',
 '

In [128]:
len(y)

17310

In [131]:
from sklearn.decomposition import PCA

In [132]:
pca = PCA(n_components=3)

In [133]:
X= pca.fit_transform(model.wv.get_normed_vectors())

In [134]:
X

array([[-0.49086   ,  0.05658833, -0.25398174],
       [-0.41334236,  0.5256119 , -0.25601065],
       [-0.5154561 , -0.13483629,  0.2786467 ],
       ...,
       [-0.4053512 ,  0.08316053, -0.09834282],
       [ 0.43397647, -0.02541653, -0.07848382],
       [-0.13651747,  0.7187831 , -0.3952671 ]], dtype=float32)

In [136]:
X.shape

(17310, 3)

In [140]:
import plotly.express as px
figure= px.scatter_3d(X[:100],x=0,y=1,z=2,color=y[:100])
figure.show()